# Welcome to Jekyll!
# 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Games and Tech and Travel oh my!
email: dohertym12@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Github Pages website where I blog about anything that interests me and experiment with website building technologies. 
  Favourite topics include Technology, Programming, Economics, Travel and TTRPGs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bigmickey.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dohertym12
github_username:  bigmickey

# Build settings
theme: minima
plugins:
  - jekyll-feed

name: Michael Doherty
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
verbose: true
collections:
  travel:
    output: true
    permalink: /travel/:path/
  crypto:
    output: true
    permalink: /crypto/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
